# Elo Merchant Category Recommendation - LightGBM with outlier detection
End date: _2019. february 19._<br/>

This tutorial notebook is the second part of a seriers for [Elo Mechant Category Recommendation](https://www.kaggle.com/c/elo-merchant-category-recommendation) contest organized by Elo, one of the largest payment brands in Brazil. It has built partnerships with merchants in order to offer promotions or discounts to cardholders. The objective of the competition is to identify and serve the most relevant opportunities to individuals, by uncovering signals in customer loyalty. The input files are available from the [download](https://www.kaggle.com/c/elo-merchant-category-recommendation/data) section of the contest:

- **train.csv**,  **test.csv**: list of `card_ids` that can be used for training and testing
- **historical_transactions.csv**: contains up to 3 months' worth of transactions for every card at any of the provided `merchant_ids`
- **new_merchant_transactions.csv**: contains the transactions at new merchants (`merchant_ids` that this particular `card_id` 
has not yet visited) over a period of two months
- **merchants.csv**: contains aggregate information for each `merchant_id` represented in the data set

In [1]:
import os
import gc
import math
import random
import warnings
import datetime
import numpy as np
import pandas as pd
import seaborn as sns
import lightgbm as lgb
import matplotlib.pyplot as plt
from keras.models import load_model
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error

warnings.filterwarnings("ignore")

random.seed(1)
threshold = 0.5

Using TensorFlow backend.

In [2]:
def reduce_mem_usage(df, verbose=True):
    numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
    start_mem = df.memory_usage().sum() / 1024**2
    if verbose: print('Starting memory usage: {:5.2f} MB'.format(start_mem))

    for col in df.columns:
        col_type = df[col].dtypes
        if col_type in numerics:
            c_min = df[col].min()
            c_max = df[col].max()
            if str(col_type)[:3] == 'int':
                if c_min >= np.iinfo(np.int8).min and c_max <= np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min >= np.iinfo(np.int16).min and c_max <= np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min >= np.iinfo(np.int32).min and c_max <= np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)
                elif c_min >= np.iinfo(np.int64).min and c_max <= np.iinfo(np.int64).max:
                    df[col] = df[col].astype(np.int64)  
            else:
                if c_min >= np.finfo(np.float16).min and c_max <= np.finfo(np.float16).max:
                    df[col] = df[col].astype(np.float16)
                elif c_min >= np.finfo(np.float32).min and c_max <= np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)    
    end_mem = df.memory_usage().sum() / 1024**2
    if verbose: print('Reduced memory usage: {:5.2f} MB ({:.1f}% reduction)'.format(end_mem, 100 * (start_mem - end_mem) / start_mem))
    return df

## Merchants

In [3]:
df_merch = pd.read_csv("input/merchants.csv")
print("{:,} records and {} features in merchant set.".format(df_merch.shape[0], df_merch.shape[1]))

334,696 records and 22 features in merchant set.

In [4]:
df_merch[:3]

,merchant_id,merchant_group_id,merchant_category_id,subsector_id,numerical_1,numerical_2,category_1,most_recent_sales_range,most_recent_purchases_range,avg_sales_lag3,...,avg_sales_lag6,avg_purchases_lag6,active_months_lag6,avg_sales_lag12,avg_purchases_lag12,active_months_lag12,category_4,city_id,state_id,category_2
0,M_ID_838061e48c,8353,792,9,-0.057471,-0.057471,N,E,E,-0.40,...,-2.25,18.666667,6,-2.32,13.916667,12,N,242,9,1.0
1,M_ID_9339d880ad,3184,840,20,-0.057471,-0.057471,N,E,E,-0.72,...,-0.74,1.291667,6,-0.57,1.687500,12,N,22,16,1.0
2,M_ID_e726bbae1e,447,690,1,-0.057471,-0.057471,N,E,E,-82.13,...,-82.13,260.000000,2,-82.13,260.000000,2,N,-1,5,5.0

In [5]:
df_merch['category_1'] = df_merch['category_1'].map({'N': 0, 'Y': 1})
df_merch['category_2'] = pd.to_numeric(df_merch['category_2'])
df_merch['category_4'] = df_merch['category_4'].map({'N': 0, 'Y': 1})
df_merch['most_recent_sales_range'] = df_merch['most_recent_sales_range'].map({'E': 0, 'D': 1, 'C': 2, 'B': 3, 'A': 4})
df_merch['most_recent_purchases_range'] = df_merch['most_recent_purchases_range'].map({'E': 0, 'D': 1, 'C': 2, 'B': 3, 'A': 4})

In [6]:
df_merch[['merchant_id', 'category_1', 'category_2', 'category_4', 'most_recent_sales_range', 'most_recent_purchases_range']][:3]

,merchant_id,category_1,category_2,category_4,most_recent_sales_range,most_recent_purchases_range
0,M_ID_838061e48c,0,1.0,0,0,0
1,M_ID_9339d880ad,0,1.0,0,0,0
2,M_ID_e726bbae1e,0,5.0,0,0,0

In [7]:
dropping = ['city_id', 'state_id']
for var in dropping:
    df_merch = df_merch.drop(var, axis=1)

In [8]:
df_merch = reduce_mem_usage(df_merch)

Starting memory usage: 51.07 MB
Reduced memory usage: 20.43 MB (60.0% reduction)

## Transactions

In [9]:
df_new_trans = pd.read_csv("input/trans_merch_new_agg.csv", index_col=0)
df_new_trans = reduce_mem_usage(df_new_trans)

df_hist_trans = pd.read_csv("input/trans_merch_hist_agg.csv", index_col=0)
df_hist_trans = reduce_mem_usage(df_hist_trans)

Starting memory usage: 354.01 MB
Reduced memory usage: 84.35 MB (76.2% reduction)
Starting memory usage: 397.39 MB
Reduced memory usage: 112.08 MB (71.8% reduction)

In [10]:
df_new_trans[:3]

,card_id,new_transactions_count,new_authorized_flag_sum,new_authorized_flag_mean,new_active_months_lag3_sum,new_active_months_lag3_mean,new_active_months_lag6_sum,new_active_months_lag6_mean,new_active_months_lag12_sum,new_active_months_lag12_mean,...,new_purchase_dayofweek_max,new_purchase_dayofweek_min,new_purchase_dayofweek_std,new_purchase_dayofweek_mode,new_purchase_quarter_mean,new_purchase_quarter_median,new_purchase_quarter_max,new_purchase_quarter_min,new_purchase_quarter_std,new_purchase_quarter_mode
0,C_ID_00007093c1,1,3,1,9.0,3.0,18.0,6.0,31.0,10.335938,...,1,0,0.577148,0,2.000000,2.0,2,2,0.000000,2
1,C_ID_0001238066,1,27,1,78.0,3.0,156.0,6.0,304.0,11.695312,...,6,0,1.764648,4,1.333008,1.0,2,1,0.480469,1
2,C_ID_0001506ef0,1,2,1,3.0,3.0,6.0,6.0,12.0,12.000000,...,4,3,0.707031,3,1.000000,1.0,1,1,0.000000,1

In [11]:
df_hist_trans[:3]

,card_id,hist_transactions_count,hist_authorized_flag_sum,hist_authorized_flag_mean,hist_active_months_lag3_sum,hist_active_months_lag3_mean,hist_active_months_lag6_sum,hist_active_months_lag6_mean,hist_active_months_lag12_sum,hist_active_months_lag12_mean,...,hist_purchase_dayofweek_max,hist_purchase_dayofweek_min,hist_purchase_dayofweek_std,hist_purchase_dayofweek_mode,hist_purchase_quarter_mean,hist_purchase_quarter_median,hist_purchase_quarter_max,hist_purchase_quarter_min,hist_purchase_quarter_std,hist_purchase_quarter_mode
0,C_ID_00007093c1,1,114.0,0.765137,447.0,3.0,894.0,6.0,1776.0,11.921875,...,6,0,1.869141,0,2.476562,2.0,4,1,1.100586,2
1,C_ID_0001238066,1,120.0,0.975586,369.0,3.0,738.0,6.0,1476.0,12.000000,...,6,0,1.909180,5,2.763672,4.0,4,1,1.471680,4
2,C_ID_0001506ef0,1,64.0,0.941406,204.0,3.0,408.0,6.0,806.0,11.851562,...,6,0,1.787109,5,2.558594,3.0,4,1,1.407227,4

## Train and test data

In [12]:
df_train = pd.read_csv("input/train.csv")
df_train = reduce_mem_usage(df_train)

df_test = pd.read_csv("input/test.csv")
df_test = reduce_mem_usage(df_test)

print("{:,} records and {} features in train set.".format(df_train.shape[0], df_train.shape[1]))
print("{:,} records and {} features in test set.".format(df_test.shape[0], df_test.shape[1]))

Starting memory usage:  9.24 MB
Reduced memory usage:  4.04 MB (56.2% reduction)
Starting memory usage:  4.72 MB
Reduced memory usage:  2.24 MB (52.5% reduction)
201,917 records and 6 features in train set.
123,623 records and 5 features in test set.

In [13]:
df_train[:3]

,first_active_month,card_id,feature_1,feature_2,feature_3,target
0,2017-06,C_ID_92a2005557,5,2,1,-0.820312
1,2017-01,C_ID_3d0044924f,4,1,0,0.392822
2,2016-08,C_ID_d639edf6cd,2,2,0,0.687988

In [14]:
df_test[:3]

  first_active_month          card_id  feature_1  feature_2  feature_3
0            2017-04  C_ID_0ab67a22ab          3          3          1
1            2017-01  C_ID_130fd0cbdd          2          3          0
2            2017-08  C_ID_b709037bc5          5          1          1

## Merging

Join the data of the merchants and the transactions to the training and test set.

In [15]:
df_train = pd.merge(df_train, df_hist_trans, on='card_id',how='left')
df_train = pd.merge(df_train, df_new_trans, on='card_id', how='left')

In [16]:
df_test = pd.merge(df_test, df_hist_trans, on='card_id',how='left')
df_test = pd.merge(df_test, df_new_trans, on='card_id', how='left')

In [17]:
del df_hist_trans
del df_new_trans
gc.collect()

35

In [18]:
df_test[:3]

,first_active_month,card_id,feature_1,feature_2,feature_3,hist_transactions_count,hist_authorized_flag_sum,hist_authorized_flag_mean,hist_active_months_lag3_sum,hist_active_months_lag3_mean,...,new_purchase_dayofweek_max,new_purchase_dayofweek_min,new_purchase_dayofweek_std,new_purchase_dayofweek_mode,new_purchase_quarter_mean,new_purchase_quarter_median,new_purchase_quarter_max,new_purchase_quarter_min,new_purchase_quarter_std,new_purchase_quarter_mode
0,2017-04,C_ID_0ab67a22ab,3,3,1,1,47.0,0.662109,213.0,3.0,...,5.0,2.0,1.527344,2.0,1.000000,1.0,1.0,1.0,0.000000,1.0
1,2017-01,C_ID_130fd0cbdd,2,3,0,1,77.0,0.987305,234.0,3.0,...,6.0,0.0,2.359375,0.0,1.400391,1.0,2.0,1.0,0.516602,1.0
2,2017-08,C_ID_b709037bc5,5,1,1,1,9.0,0.692383,39.0,3.0,...,3.0,1.0,1.414062,1.0,1.000000,1.0,1.0,1.0,0.000000,1.0

## Outlier detection

In [19]:
cols = ['feature_1', 'feature_2', 'feature_3', 'hist_authorized_flag_sum', 'hist_active_months_lag3_sum', 'hist_active_months_lag6_sum', 'hist_active_months_lag12_sum', 'hist_avg_sales_lag3_sum', 'hist_avg_sales_lag3_mean', 'hist_avg_sales_lag6_sum', 'hist_avg_sales_lag6_mean', 'hist_avg_sales_lag12_sum', 'hist_avg_sales_lag12_mean', 'hist_category_1_trans_sum', 'hist_category_1_merch_sum', 'hist_category_2_trans_sum', 'hist_category_2_trans_mean', 'hist_category_2_trans_nancnt', 'hist_category_2_trans_nanperc', 'hist_category_2_merch_sum', 'hist_category_2_merch_mean', 'hist_category_2_merch_nancnt', 'hist_category_2_merch_nanperc', 'hist_category_3_sum', 'hist_category_3_nanperc', 'hist_category_4_sum', 'hist_city_id_nunique', 'hist_city_id_mode', 'hist_installments_sum', 'hist_installments_mean', 'hist_installments_max', 'hist_installments_min', 'hist_installments_std', 'hist_installments_mode', 'hist_merchant_id_nunique', 'hist_merchant_id_nancnt', 'hist_merchant_category_id_trans_nunique', 'hist_merchant_category_id_trans_mode', 'hist_merchant_group_id_nunique', 'hist_merchant_group_id_mode', 'hist_merchant_category_id_merch_nunique', 'hist_merchant_category_id_merch_mode', 'hist_month_lag_min', 'hist_month_lag_max', 'hist_month_lag_mean', 'hist_most_recent_sales_range_sum', 'hist_most_recent_sales_range_max', 'hist_most_recent_sales_range_mode', 'hist_most_recent_purchases_range_sum', 'hist_most_recent_purchases_range_max', 'hist_most_recent_purchases_range_mode', 'hist_numerical_1_mean', 'hist_numerical_1_std', 'hist_numerical_1_mode', 'hist_numerical_2_mean', 'hist_numerical_2_std', 'hist_state_id_nunique', 'hist_state_id_mode', 'hist_subsector_id_trans_nunique', 'hist_subsector_id_trans_mode', 'hist_subsector_id_merch_nunique', 'hist_subsector_id_merch_mode', 'hist_purchase_amount_sum', 'hist_purchase_amount_mean', 'hist_purchase_amount_max', 'hist_purchase_amount_std', 'hist_purchase_year_mean', 'hist_purchase_year_median', 'hist_purchase_year_max', 'hist_purchase_year_mode', 'hist_purchase_month_mean', 'hist_purchase_month_median', 'hist_purchase_month_max', 'hist_purchase_month_min', 'hist_purchase_month_std', 'hist_purchase_month_mode', 'hist_purchase_day_mean', 'hist_purchase_day_median', 'hist_purchase_day_max', 'hist_purchase_day_min', 'hist_purchase_day_std', 'hist_purchase_day_mode', 'hist_purchase_hour_mean', 'hist_purchase_hour_median', 'hist_purchase_hour_max', 'hist_purchase_hour_min', 'hist_purchase_hour_std', 'hist_purchase_hour_mode', 'hist_purchase_weekofyear_mean', 'hist_purchase_weekofyear_median', 'hist_purchase_weekofyear_max', 'hist_purchase_weekofyear_min', 'hist_purchase_weekofyear_std', 'hist_purchase_weekofyear_mode', 'hist_purchase_dayofweek_median', 'hist_purchase_dayofweek_max', 'hist_purchase_dayofweek_min', 'hist_purchase_dayofweek_mode', 'hist_purchase_quarter_median', 'hist_purchase_quarter_max', 'hist_purchase_quarter_min', 'hist_purchase_quarter_mode', 'new_authorized_flag_sum', 'new_active_months_lag3_sum', 'new_active_months_lag3_mean', 'new_active_months_lag6_sum', 'new_active_months_lag12_sum', 'new_avg_sales_lag3_sum', 'new_avg_sales_lag3_mean', 'new_avg_sales_lag6_sum', 'new_avg_sales_lag6_mean', 'new_avg_sales_lag12_sum', 'new_avg_sales_lag12_mean', 'new_avg_purchases_lag3_sum', 'new_avg_purchases_lag3_mean', 'new_avg_purchases_lag6_sum', 'new_avg_purchases_lag6_mean', 'new_avg_purchases_lag12_sum', 'new_avg_purchases_lag12_mean', 'new_category_1_trans_sum', 'new_category_1_merch_sum', 'new_category_2_trans_sum', 'new_category_2_trans_mean', 'new_category_2_trans_nanperc', 'new_category_2_merch_sum', 'new_category_2_merch_nancnt', 'new_category_2_merch_nanperc', 'new_category_3_sum', 'new_category_3_nanperc', 'new_category_4_sum', 'new_city_id_nunique', 'new_city_id_mode', 'new_installments_sum', 'new_installments_max', 'new_installments_min', 'new_installments_mode', 'new_merchant_id_nunique', 'new_merchant_id_nancnt', 'new_merchant_id_nanperc', 'new_merchant_category_id_trans_nunique', 'new_merchant_category_id_trans_mode', 'new_merchant_group_id_nunique', 'new_merchant_group_id_mode', 'new_merchant_group_id_nanperc', 'new_merchant_category_id_merch_nunique', 'new_merchant_category_id_merch_mode', 'new_merchant_category_id_merch_nanperc', 'new_month_lag_min', 'new_month_lag_max', 'new_most_recent_sales_range_sum', 'new_most_recent_sales_range_max', 'new_most_recent_sales_range_mode', 'new_most_recent_purchases_range_sum', 'new_most_recent_purchases_range_max', 'new_most_recent_purchases_range_min', 'new_most_recent_purchases_range_mode', 'new_numerical_1_mean', 'new_numerical_1_median', 'new_numerical_1_max', 'new_numerical_1_std', 'new_numerical_2_mean', 'new_numerical_2_median', 'new_numerical_2_max', 'new_numerical_2_std', 'new_state_id_nunique', 'new_state_id_mode', 'new_subsector_id_trans_nunique', 'new_subsector_id_trans_mode', 'new_subsector_id_merch_nunique', 'new_subsector_id_merch_mode', 'new_subsector_id_merch_nanperc', 'new_purchase_amount_sum', 'new_purchase_year_mean', 'new_purchase_year_median', 'new_purchase_year_max', 'new_purchase_year_min', 'new_purchase_year_mode', 'new_purchase_month_mean', 'new_purchase_month_median', 'new_purchase_month_max', 'new_purchase_month_min', 'new_purchase_month_mode', 'new_purchase_day_mean', 'new_purchase_day_median', 'new_purchase_day_max', 'new_purchase_day_min', 'new_purchase_day_std', 'new_purchase_day_mode', 'new_purchase_hour_mean', 'new_purchase_hour_median', 'new_purchase_hour_max', 'new_purchase_hour_min', 'new_purchase_hour_std', 'new_purchase_hour_mode', 'new_purchase_weekofyear_mean', 'new_purchase_weekofyear_median', 'new_purchase_weekofyear_max', 'new_purchase_weekofyear_min', 'new_purchase_weekofyear_std', 'new_purchase_weekofyear_mode', 'new_purchase_dayofweek_mean', 'new_purchase_dayofweek_median', 'new_purchase_dayofweek_max', 'new_purchase_dayofweek_min', 'new_purchase_dayofweek_mode', 'new_purchase_quarter_mean', 'new_purchase_quarter_median', 'new_purchase_quarter_max', 'new_purchase_quarter_min', 'new_purchase_quarter_mode']

df_test_o = df_test.copy(deep=True)
df_test_o = df_test_o[cols].dropna(how='any', axis=0)

In [20]:
df_test[cols][:3]

,feature_1,feature_2,feature_3,hist_authorized_flag_sum,hist_active_months_lag3_sum,hist_active_months_lag6_sum,hist_active_months_lag12_sum,hist_avg_sales_lag3_sum,hist_avg_sales_lag3_mean,hist_avg_sales_lag6_sum,...,new_purchase_dayofweek_mean,new_purchase_dayofweek_median,new_purchase_dayofweek_max,new_purchase_dayofweek_min,new_purchase_dayofweek_mode,new_purchase_quarter_mean,new_purchase_quarter_median,new_purchase_quarter_max,new_purchase_quarter_min,new_purchase_quarter_mode
0,3,3,1,47.0,213.0,426.0,837.0,100.729996,1.418732,110.570000,...,3.666016,4.0,5.0,2.0,2.0,1.000000,1.0,1.0,1.0,1.0
1,2,3,0,77.0,234.0,468.0,936.0,79.639999,1.021026,80.120003,...,2.699219,3.0,6.0,0.0,0.0,1.400391,1.0,2.0,1.0,1.0
2,5,1,1,9.0,39.0,78.0,156.0,13.670000,1.051538,12.940000,...,2.000000,2.0,3.0,1.0,1.0,1.000000,1.0,1.0,1.0,1.0

In [21]:
df_test_o[:3]

,feature_1,feature_2,feature_3,hist_authorized_flag_sum,hist_active_months_lag3_sum,hist_active_months_lag6_sum,hist_active_months_lag12_sum,hist_avg_sales_lag3_sum,hist_avg_sales_lag3_mean,hist_avg_sales_lag6_sum,...,new_purchase_dayofweek_mean,new_purchase_dayofweek_median,new_purchase_dayofweek_max,new_purchase_dayofweek_min,new_purchase_dayofweek_mode,new_purchase_quarter_mean,new_purchase_quarter_median,new_purchase_quarter_max,new_purchase_quarter_min,new_purchase_quarter_mode
0,3,3,1,47.0,213.0,426.0,837.0,100.729996,1.418732,110.570000,...,3.666016,4.0,5.0,2.0,2.0,1.000000,1.0,1.0,1.0,1.0
1,2,3,0,77.0,234.0,468.0,936.0,79.639999,1.021026,80.120003,...,2.699219,3.0,6.0,0.0,0.0,1.400391,1.0,2.0,1.0,1.0
2,5,1,1,9.0,39.0,78.0,156.0,13.670000,1.051538,12.940000,...,2.000000,2.0,3.0,1.0,1.0,1.000000,1.0,1.0,1.0,1.0

In [27]:
df_test['hist_category_1_trans_sum'].max()

5580.0

In [98]:
def safeCalculateMeanStd(series):
    c = len(series)
    s = 0

    for i in range(0, c):
        if math.isfinite(series.iloc[i]):
            s = s + series.iloc[i]

    mean = s/c
    std = np.sqrt(np.sum(np.power(series-mean, 2))/c)
    return mean, std

In [100]:
df_test['hist_authorized_flag_sum'][:3]

0    47.0
1    77.0
2     9.0
Name: hist_authorized_flag_sum, dtype: float16

In [99]:
safeCalculateMeanStd(df_test['hist_authorized_flag_sum'])

(85.34093979275701, inf)

In [ ]:
for f in df_test_o.columns:
    m, s = safeCalculateMeanStd()
    df_test_o[f] = (df_test_o[f] - m)/s
    print('{}: {:.4f} ({:.4f}), min: {:,.4f}, max:{:,}'.format(f, m, s, df_test_o[f].min(), df_test_o[f].max()))

In [23]:
for f in df_test_o.columns:
    mean = df_test_o[f].mean()
    std = df_test_o[f].std()
    if math.isnan(mean):
        mean = df_test_o[f].astype(int).mean()
        std = df_test_o[f].astype(int).std()
    
    df_test_o[f] = (df_test_o[f] - mean)/std
    print('{}: {:.4f} ({:.4f}), min: {:,.4f}, max:{:,}'.format(f, mean, std, df_test_o[f].min(), df_test_o[f].max()))

feature_1: 0.0000 (1.0000), min: -1.7465, max:1.5902910120465035
feature_2: 0.0000 (1.0000), min: -0.9736, max:1.700517940241105
feature_3: -0.0000 (1.0000), min: -1.1158, max:0.8961863550258807
hist_authorized_flag_sum: 0.0000 (0.0000), min: -inf, max:inf
hist_active_months_lag3_sum: 0.0000 (0.0000), min: -inf, max:inf
hist_active_months_lag6_sum: 0.0000 (0.0000), min: -inf, max:inf
hist_active_months_lag12_sum: 0.0000 (1.0000), min: -0.8696, max:14.036707020068151
hist_avg_sales_lag3_sum: -0.0000 (1.0000), min: -0.0804, max:87.19811248779297
hist_avg_sales_lag3_mean: -0.0000 (1.0000), min: -0.0549, max:142.02964782714844
hist_avg_sales_lag6_sum: -0.0000 (1.0000), min: -0.0821, max:85.44084930419922
hist_avg_sales_lag6_mean: 0.0000 (1.0000), min: -0.0533, max:129.2336883544922
hist_avg_sales_lag12_sum: 0.0000 (1.0000), min: -0.0816, max:82.40811920166016
hist_avg_sales_lag12_mean: 0.0000 (1.0000), min: -0.0474, max:126.52336883544922
hist_category_1_trans_sum: -0.0000 (0.0000), min: -inf, max:inf
hist_category_1_merch_sum: 0.0000 (0.0000), min: -inf, max:inf
hist_category_2_trans_sum: 0.0000 (0.0000), min: -inf, max:inf
hist_category_2_trans_mean: 1.8703 (1.1617), min: -0.7485, max:2.693359375
hist_category_2_trans_nancnt: 7.5091 (24.4217), min: -0.3074, max:45.40625
hist_category_2_trans_nanperc: 8.2992 (16.4346), min: -0.5049, max:5.54296875
hist_category_2_merch_sum: 197.7300 (313.3543), min: -0.6279, max:22.5
hist_category_2_merch_mean: 2.1206 (1.3980), min: -0.8018, max:2.05859375
hist_category_2_merch_nancnt: 17.8980 (29.8773), min: -0.5986, max:38.0
hist_category_2_merch_nanperc: 18.2663 (17.9093), min: -1.0205, max:4.546875
hist_category_3_sum: 54.5682 (95.0689), min: -0.5737, max:15.0859375
hist_category_3_nanperc: 1.0858 (3.4738), min: -0.3125, max:21.28125
hist_category_4_sum: 55.7735 (89.2926), min: -0.6245, max:17.84375
hist_city_id_nunique: 5.3663 (3.6758), min: -1.1879, max:24.385100984052944
hist_city_id_mode: 135.3294 (104.7003), min: -1.3021, max:2.0216812340396153
hist_installments_sum: 66.0214 (115.7101), min: -0.5879, max:54.17832082672479
hist_installments_mean: 0.6398 (1.0823), min: -1.0537, max:132.625
hist_installments_max: 4.3783 (24.9174), min: -0.1757, max:39.91675856909297
hist_installments_min: 0.0003 (0.7189), min: -1.3914, max:8.346095150996566
hist_installments_std: 0.4865 (3.3276), min: -0.1462, max:113.125
hist_installments_mode: 0.5601 (0.7338), min: -2.1261, max:15.590296623001173
hist_merchant_id_nunique: 38.4539 (32.8241), min: -1.1411, max:11.776292288690984
hist_merchant_id_nancnt: 0.5046 (1.3791), min: -0.3659, max:51.116720711919356
hist_merchant_category_id_trans_nunique: 20.2163 (11.7433), min: -1.6364, max:6.1127562680016485
hist_merchant_category_id_trans_mode: 534.3757 (250.2477), min: -2.1394, max:1.4250851879482558
hist_merchant_group_id_nunique: 26.3621 (22.5629), min: -1.1241, max:12.571010285873985
hist_merchant_group_id_mode: 6022.0522 (19407.7363), min: -0.3102, max:5.489354610443115
hist_merchant_category_id_merch_nunique: 19.3892 (11.1219), min: -1.6534, max:5.9891425244991146
hist_merchant_category_id_merch_mode: 492.5978 (221.3734), min: -2.2148, max:1.7998046875
hist_month_lag_min: -7.5876 (3.8803), min: -1.3948, max:1.697704984647615
hist_month_lag_max: -0.1259 (0.5616), min: -19.3636, max:0.2241079534043957
hist_month_lag_mean: -3.1305 (2.0920), min: -4.4609, max:1.478515625
hist_most_recent_sales_range_sum: 245.8013 (285.0522), min: -0.8623, max:16.203125
hist_most_recent_sales_range_max: 3.9628 (0.2213), min: -17.9062, max:0.167724609375
hist_most_recent_sales_range_mode: 2.7679 (1.2151), min: -2.2773, max:1.0146484375
hist_most_recent_purchases_range_sum: 253.7094 (298.1870), min: -0.8506, max:16.515625
hist_most_recent_purchases_range_max: 3.9605 (0.2327), min: -17.0312, max:0.1678466796875
hist_most_recent_purchases_range_mode: 2.7924 (1.2229), min: -2.2852, max:0.9873046875
hist_numerical_1_mean: 4.4882 (8.2092), min: -0.5537, max:19.625
hist_numerical_1_std: 11.7764 (15.4176), min: -0.7637, max:5.69921875
hist_numerical_1_mode: 1.1140 (10.6479), min: -0.1100, max:17.15625
hist_numerical_2_mean: 4.3774 (8.0796), min: -0.5493, max:19.796875
hist_numerical_2_std: 11.6365 (15.2398), min: -0.7632, max:5.703125
hist_state_id_nunique: 2.8844 (1.5923), min: -1.1835, max:12.005147779500932
hist_state_id_mode: 11.1168 (6.0907), min: -1.9894, max:2.1152280130837307
hist_subsector_id_trans_nunique: 12.3884 (5.0779), min: -2.2427, max:4.256046598638566
hist_subsector_id_trans_mode: 28.4279 (8.2747), min: -3.5564, max:1.5193481288227098
hist_subsector_id_merch_nunique: 12.4003 (5.0562), min: -2.2547, max:4.469665881804665
hist_subsector_id_merch_mode: 25.7648 (10.8822), min: -2.2754, max:1.3994140625
hist_purchase_amount_sum: -21.7114 (1431.0861), min: -0.8255, max:96.41100311279297
hist_purchase_amount_mean: -0.1732 (22.6213), min: -0.0252, max:239.87001037597656
hist_purchase_amount_max: 39.5697 (1418.9038), min: -0.0284, max:95.6558837890625
hist_purchase_amount_std: 3.6231 (142.1104), min: -0.0255, max:161.98275756835938
hist_purchase_year_mean: 2017.1316 (0.3381), min: 0.0000, max:2.95703125
hist_purchase_year_median: 2017.1316 (0.3381), min: 0.0000, max:2.95703125
hist_purchase_year_max: 2017.7636 (0.4249), min: -1.7972, max:0.5564238512346062
hist_purchase_year_mode: 2017.1229 (0.3283), min: -0.3743, max:2.6713404680098654
hist_purchase_month_mean: 6.0379 (1.8680), min: -2.6348, max:3.169921875
hist_purchase_month_median: 6.7104 (3.0133), min: -1.8945, max:1.7548828125
hist_purchase_month_max: 11.2325 (1.8592), min: -4.9658, max:0.4127798711958444
hist_purchase_month_min: 1.5485 (1.6536), min: -0.3317, max:5.71564551905154
hist_purchase_month_std: 2.9573 (1.2225), min: -2.3027, max:3.943359375
hist_purchase_month_mode: 5.9997 (4.2887), min: -1.1658, max:1.399099053987529
hist_purchase_day_mean: 15.4818 (2.6080), min: -5.2188, max:5.5234375
hist_purchase_day_median: 15.9665 (4.0183), min: -3.7246, max:3.740234375
hist_purchase_day_max: 29.8777 (2.1846), min: -11.8457, max:0.5137622694098429
hist_purchase_day_min: 2.0214 (2.2595), min: -0.4520, max:11.497674869171908
hist_purchase_day_std: 7.7666 (1.4339), min: -5.4180, max:7.41015625
hist_purchase_day_mode: 14.4543 (8.4599), min: -1.5904, max:1.9557822906800648
hist_purchase_hour_mean: 13.6216 (1.5257), min: -7.8828, max:5.4921875
hist_purchase_hour_median: 14.5672 (1.9869), min: -7.3320, max:3.73828125
hist_purchase_hour_max: 22.0733 (1.5068), min: -10.0035, max:0.6150038352212507
hist_purchase_hour_min: 1.9224 (3.5180), min: -0.5465, max:5.707134596297331
hist_purchase_hour_std: 4.5810 (1.3439), min: -3.4102, max:4.86328125
hist_purchase_hour_mode: 13.5966 (5.0859), min: -2.6734, max:1.8489267448765987
hist_purchase_weekofyear_mean: 26.0702 (8.0185), min: -3.0117, max:3.064453125
hist_purchase_weekofyear_median: 27.3436 (12.9680), min: -2.0312, max:1.9013671875
hist_purchase_weekofyear_max: 48.2529 (7.9847), min: -5.2917, max:0.4692868283638856
hist_purchase_weekofyear_min: 4.0393 (7.4844), min: -0.4061, max:5.873632718962499
hist_purchase_weekofyear_std: 14.5975 (5.1201), min: -2.8496, max:4.19140625
hist_purchase_weekofyear_mode: 23.7185 (18.3738), min: -1.2365, max:1.5392285245679926
hist_purchase_dayofweek_median: 3.1002 (0.8809), min: -3.5195, max:3.29296875
hist_purchase_dayofweek_max: 5.8622 (0.4280), min: -13.6970, max:0.32185919821254194
hist_purchase_dayofweek_min: 0.0732 (0.3407), min: -0.2149, max:14.462782242603968
hist_purchase_dayofweek_mode: 3.2054 (1.8217), min: -1.7596, max:1.5340534043262393
hist_purchase_quarter_median: 2.5712 (1.0339), min: -1.5186, max:1.3828125
hist_purchase_quarter_max: 3.8218 (0.5364), min: -5.2610, max:0.3321944660168939
hist_purchase_quarter_min: 1.1315 (0.4728), min: -0.2782, max:6.066343821142798
hist_purchase_quarter_mode: 2.4943 (1.3199), min: -1.1321, max:1.1408073286615577
new_authorized_flag_sum: 7.9500 (6.8023), min: -0.8747, max:14.267226373809686
new_active_months_lag3_sum: 23.5579 (20.2830), min: -0.9150, max:14.2265625
new_active_months_lag3_mean: 2.9990 (0.0322), min: -20.6406, max:0.06072998046875
new_active_months_lag6_sum: 47.0469 (40.5048), min: -0.9644, max:14.1953125
new_active_months_lag12_sum: 92.5436 (80.0711), min: -1.0059, max:13.953125
new_avg_sales_lag3_sum: 311.6224 (15957.0635), min: -0.0195, max:53.36853790283203
new_avg_sales_lag3_mean: 33.6366 (2065.6169), min: -0.0161, max:137.4481964111328
new_avg_sales_lag6_sum: 295.3674 (14550.0781), min: -0.0202, max:52.93798828125
new_avg_sales_lag6_mean: 32.0208 (1870.3021), min: -0.0169, max:137.2949981689453
new_avg_sales_lag12_sum: 269.4195 (13079.9551), min: -0.0205, max:52.712154388427734
new_avg_sales_lag12_mean: 29.2235 (1675.0072), min: -0.0172, max:137.2086181640625
new_avg_purchases_lag3_sum: 33.2244 (1156.7863), min: -0.0278, max:54.40625
new_avg_purchases_lag3_mean: 3.6133 (150.1216), min: -0.0206, max:137.375
new_avg_purchases_lag6_sum: 62.1145 (1062.5494), min: -0.0576, max:55.96875
new_avg_purchases_lag6_mean: 7.9238 (139.4640), min: -0.0538, max:134.0
new_avg_purchases_lag12_sum: 65.4129 (966.7097), min: -0.0670, max:57.34375
new_avg_purchases_lag12_mean: 8.4764 (128.7416), min: -0.0630, max:129.875
new_category_1_trans_sum: 0.2336 (0.6489), min: -0.3600, max:25.838631632680627
new_category_1_merch_sum: 0.7806 (1.1500), min: -0.6787, max:13.2265625
new_category_2_trans_sum: 16.5819 (20.2551), min: -0.7695, max:24.171875

new_category_2_trans_mean: 2.0550 (1.3539), min: -0.7793, max:2.17578125
new_category_2_trans_nanperc: 4.9450 (12.8257), min: -0.3855, max:7.23046875
new_category_2_merch_sum: 15.7729 (19.9443), min: -0.7910, max:22.578125
new_category_2_merch_nancnt: 0.9300 (1.4278), min: -0.6514, max:29.46875
new_category_2_merch_nanperc: 13.1097 (19.6527), min: -0.6670, max:4.41796875
new_category_3_sum: 4.5891 (6.9276), min: -0.6626, max:12.484375
new_category_3_nanperc: 3.3046 (9.8295), min: -0.3362, max:9.8359375
new_category_4_sum: 3.9952 (5.1821), min: -0.7710, max:14.2734375
new_city_id_nunique: 2.5574 (1.6966), min: -0.9179, max:17.353973327552534
new_city_id_mode: 128.2978 (99.5543), min: -1.2988, max:2.196812536355067
new_installments_sum: 5.4142 (9.1464), min: -0.9199, max:109.06851601373235
new_installments_max: 1.5680 (4.1087), min: -0.6250, max:242.76109989987685
new_installments_min: 0.2205 (0.7470), min: -1.6339, max:15.769633318693558
new_installments_mode: 0.5091 (0.7395), min: -2.0408, max:15.539756433681882
new_merchant_id_nunique: 7.7239 (6.7124), min: -1.0017, max:14.194096187848647
new_merchant_id_nancnt: 0.0968 (0.2960), min: -0.3272, max:6.429641456900091
new_merchant_id_nanperc: 1.2625 (4.6554), min: -0.2712, max:8.3203125
new_merchant_category_id_trans_nunique: 6.1286 (4.1923), min: -1.2233, max:9.510525420653112
new_merchant_category_id_trans_mode: 313.3447 (241.0264), min: -1.3042, max:2.3966477696725064
new_merchant_group_id_nunique: 6.1709 (5.1654), min: -1.0011, max:13.518567901575693
new_merchant_group_id_mode: 1788.8519 (8005.0430), min: -0.2233, max:13.526617050170898
new_merchant_group_id_nanperc: 1.2625 (4.6554), min: -0.2712, max:8.3203125
new_merchant_category_id_merch_nunique: 6.0439 (4.1542), min: -1.2142, max:9.377487250539525
new_merchant_category_id_merch_mode: 294.1168 (210.6950), min: -1.3857, max:2.83203125
new_merchant_category_id_merch_nanperc: 1.2625 (4.6554), min: -0.2712, max:8.3203125
new_month_lag_min: 1.1043 (0.3057), min: -0.3413, max:2.929785048252398
new_month_lag_max: 1.8749 (0.3308), min: -2.6445, max:0.3781367235592049
new_most_recent_sales_range_sum: 16.1149 (13.9963), min: -1.1504, max:13.9921875
new_most_recent_sales_range_max: 3.5165 (0.7997), min: -4.3945, max:0.60546875
new_most_recent_sales_range_mode: 1.7514 (1.2237), min: -1.4307, max:1.8388671875
new_most_recent_purchases_range_sum: 16.4121 (14.3804), min: -1.1406, max:14.8515625
new_most_recent_purchases_range_max: 3.5192 (0.8168), min: -4.3086, max:0.58837890625
new_most_recent_purchases_range_min: 0.7283 (0.8464), min: -0.8604, max:3.865234375
new_most_recent_purchases_range_mode: 1.7631 (1.1965), min: -1.4736, max:1.87109375
new_numerical_1_mean: 3.3180 (8.4075), min: -0.4014, max:18.21875
new_numerical_1_median: 0.8567 (5.8066), min: -0.1575, max:26.8125
new_numerical_1_max: 19.5510 (39.4780), min: -0.4968, max:4.16015625
new_numerical_1_std: 6.8805 (14.6478), min: -0.4695, max:8.40625
new_numerical_2_mean: 3.2412 (8.2708), min: -0.3987, max:18.375
new_numerical_2_median: 0.8339 (5.7244), min: -0.1558, max:26.96875
new_numerical_2_max: 19.2097 (38.8784), min: -0.4956, max:4.19140625
new_numerical_2_std: 6.7736 (14.4283), min: -0.4695, max:8.453125
new_state_id_nunique: 1.6913 (0.9126), min: -0.7576, max:14.583894633182634
new_state_id_mode: 11.0684 (5.8904), min: -2.0488, max:2.1953792241483883
new_subsector_id_trans_nunique: 5.0789 (2.9356), min: -1.3895, max:6.1048523968201405
new_subsector_id_trans_mode: 23.2978 (10.7903), min: -2.2518, max:1.64057071544497
new_subsector_id_merch_nunique: 5.0450 (2.9351), min: -1.3781, max:5.776572698691947
new_subsector_id_merch_mode: 21.7957 (11.4378), min: -1.8184, max:1.6787109375
new_subsector_id_merch_nanperc: 1.2625 (4.6554), min: -0.2712, max:8.3203125
new_purchase_amount_sum: -3.9337 (4.5787), min: -12.4141, max:38.4375
new_purchase_year_mean: 2017.8557 (0.3513), min: -2.8457, max:0.0
new_purchase_year_median: 2017.8557 (0.3513), min: -2.8457, max:0.0
new_purchase_year_max: 2017.8688 (0.3376), min: -2.5736, max:0.3885616087986988
new_purchase_year_min: 2017.8435 (0.3633), min: -2.3214, max:0.43076186856829485
new_purchase_year_mode: 2017.8519 (0.3552), min: -2.3982, max:0.41697382064756333
new_purchase_month_mean: 3.7100 (2.2347), min: -1.2129, max:3.708984375
new_purchase_month_median: 4.0176 (2.3964), min: -1.2598, max:3.330078125
new_purchase_month_max: 4.5932 (2.4547), min: -1.4638, max:3.0174708557202266
new_purchase_month_min: 3.5692 (2.1975), min: -1.1691, max:3.8364783945665706
new_purchase_month_mode: 3.9983 (2.4004), min: -1.2491, max:3.3334202839443274
new_purchase_day_mean: 15.2840 (5.1939), min: -2.7480, max:3.025390625
new_purchase_day_median: 15.5307 (6.5087), min: -2.2324, max:2.376953125
new_purchase_day_max: 24.4136 (6.5936), min: -3.5510, max:0.9988998437102602
new_purchase_day_min: 6.9749 (6.3042), min: -0.9478, max:3.8109957282633378
new_purchase_day_std: 6.6501 (3.5580), min: -1.8682, max:4.09375
new_purchase_day_mode: 12.2917 (8.5859), min: -1.3152, max:2.1789631717363815
new_purchase_hour_mean: 13.1226 (2.4885), min: -5.2734, max:3.96875
new_purchase_hour_median: 13.5012 (2.9288), min: -4.6094, max:3.2421875
new_purchase_hour_max: 18.4303 (3.3671), min: -5.4737, max:1.3571666975213115
new_purchase_hour_min: 8.1263 (4.0919), min: -1.9860, max:3.634938308532761
new_purchase_hour_std: 3.4993 (1.9505), min: -1.7949, max:6.546875
new_purchase_hour_mode: 11.5988 (4.5158), min: -2.5685, max:2.52475566617906
new_purchase_weekofyear_mean: 15.4686 (9.7073), min: -1.4902, max:3.76171875
new_purchase_weekofyear_median: 15.7910 (10.2929), min: -1.4375, max:3.51953125
new_purchase_weekofyear_max: 18.8410 (10.7244), min: -1.6636, max:3.091933544144627
new_purchase_weekofyear_min: 12.7909 (9.6068), min: -1.2274, max:4.081398193106695
new_purchase_weekofyear_std: 2.1484 (3.6420), min: -0.5898, max:9.3046875
new_purchase_weekofyear_mode: 15.0560 (10.4053), min: -1.3509, max:3.550498292423734
new_purchase_dayofweek_mean: 2.7047 (1.0840), min: -2.4961, max:3.0390625
new_purchase_dayofweek_median: 3.0817 (1.3732), min: -2.2441, max:2.125
new_purchase_dayofweek_max: 4.9958 (1.2454), min: -4.0113, max:0.8062797717734896
new_purchase_dayofweek_min: 0.9982 (1.3559), min: -0.7362, max:3.68883283770536
new_purchase_dayofweek_mode: 2.6604 (1.9316), min: -1.3773, max:1.7288980090706254
new_purchase_quarter_mean: 1.3841 (0.8199), min: -0.4680, max:3.19140625
new_purchase_quarter_median: 1.6144 (0.8739), min: -0.7026, max:2.73046875
new_purchase_quarter_max: 2.0103 (0.7955), min: -1.2700, max:2.5011370324988387
new_purchase_quarter_min: 1.3529 (0.8037), min: -0.4391, max:3.2934873320972438
new_purchase_quarter_mode: 1.6105 (0.8744), min: -0.6982, max:2.7328491936354444

In [24]:
df_test[cols][:3]

,feature_1,feature_2,feature_3,hist_authorized_flag_sum,hist_active_months_lag3_sum,hist_active_months_lag6_sum,hist_active_months_lag12_sum,hist_avg_sales_lag3_sum,hist_avg_sales_lag3_mean,hist_avg_sales_lag6_sum,...,new_purchase_dayofweek_mean,new_purchase_dayofweek_median,new_purchase_dayofweek_max,new_purchase_dayofweek_min,new_purchase_dayofweek_mode,new_purchase_quarter_mean,new_purchase_quarter_median,new_purchase_quarter_max,new_purchase_quarter_min,new_purchase_quarter_mode
0,3,3,1,47.0,213.0,426.0,837.0,100.729996,1.418732,110.570000,...,3.666016,4.0,5.0,2.0,2.0,1.000000,1.0,1.0,1.0,1.0
1,2,3,0,77.0,234.0,468.0,936.0,79.639999,1.021026,80.120003,...,2.699219,3.0,6.0,0.0,0.0,1.400391,1.0,2.0,1.0,1.0
2,5,1,1,9.0,39.0,78.0,156.0,13.670000,1.051538,12.940000,...,2.000000,2.0,3.0,1.0,1.0,1.000000,1.0,1.0,1.0,1.0

In [25]:
df_test_o[:3]

,feature_1,feature_2,feature_3,hist_authorized_flag_sum,hist_active_months_lag3_sum,hist_active_months_lag6_sum,hist_active_months_lag12_sum,hist_avg_sales_lag3_sum,hist_avg_sales_lag3_mean,hist_avg_sales_lag6_sum,...,new_purchase_dayofweek_mean,new_purchase_dayofweek_median,new_purchase_dayofweek_max,new_purchase_dayofweek_min,new_purchase_dayofweek_mode,new_purchase_quarter_mean,new_purchase_quarter_median,new_purchase_quarter_max,new_purchase_quarter_min,new_purchase_quarter_mode
0,-0.078127,1.700518,0.896186,-inf,-inf,-inf,-0.282577,-0.079763,-0.054461,-0.081428,...,0.886719,0.668457,0.003354,0.738822,-0.341886,-0.468018,-0.702637,-1.270005,-0.439056,-0.698217
1,-0.912336,1.700518,-1.115827,-inf,-inf,-inf,-0.211100,-0.079890,-0.054627,-0.081627,...,-0.005405,-0.059753,0.806280,-0.736183,-1.377277,0.020248,-0.702637,-0.012957,-0.439056,-0.698217
2,1.590291,-0.973629,0.896186,-inf,-inf,-inf,-0.774254,-0.080287,-0.054614,-0.082065,...,-0.650391,-0.788086,-1.602496,0.001319,-0.859581,-0.468018,-0.702637,-1.270005,-0.439056,-0.698217

In [ ]:
autoencoder = load_model('models/autoencoder_3relu_30-15_t1.8.h5')

In [ ]:
pred_o = autoencoder.predict(df_test_o)

In [ ]:
def createReconstructionError(autoencoder, X_test):
    predictions = autoencoder.predict(X_test)
    mse = np.mean(np.power(X_test - predictions, 2), axis=1)
    error_df = pd.DataFrame({
        'reconstruction_error': mse
    })

    return error_df

In [ ]:
len(df_test_o), len(pred_o)

In [ ]:
pd.set_option('display.float_format', '{:.2f}'.format)

error_df = createReconstructionError(autoencoder, df_test_o)
error_df.describe()

In [ ]:
df_test_o[:10]

In [ ]:
df_test.shape, df_test_o.shape, pred_o.shape, error_df.shape

In [ ]:
df_test[cols][:3]

In [ ]:
df_test_o[:3]

## Training
### LightGBM
For more details click [here](https://lightgbm.readthedocs.io/en/latest/).

In [ ]:
df_train.drop(columns=['new_merchant_id_mode', 'hist_merchant_id_mode'], inplace=True, axis=1)
df_test.drop(columns=['new_merchant_id_mode', 'hist_merchant_id_mode'], inplace=True, axis=1)

In [ ]:
target = df_train['target']
drops = ['card_id', 'first_active_month', 'target']
use_cols = [c for c in df_train.columns if c not in drops]
features = list(df_train[use_cols].columns)
df_train[features][:3]

In [ ]:
param = {
    'num_leaves': 50,
    'min_data_in_leaf': 30, 
    'objective':'regression',
    'max_depth': -1,
    'learning_rate': 0.005,
    "boosting": "gbdt",
    "feature_fraction": 0.9,
    "bagging_freq": 1,
    "bagging_fraction": 0.9,
    "bagging_seed": 11,
    "metric": 'rmse',
    "lambda_l1": 0.1,
    "verbosity": -1
}

folds = KFold(n_splits=5, shuffle=True, random_state=15)

oof = np.zeros(len(df_train))
predictions = np.zeros(len(df_test))

feature_importance_df = pd.DataFrame()

for fold_, (trn_idx, val_idx) in enumerate(folds.split(df_train.values, target.values)):
    print('-')
    print("Fold {}".format(fold_ + 1))
    trn_data = lgb.Dataset(df_train.iloc[trn_idx][features], label=target.iloc[trn_idx])
    val_data = lgb.Dataset(df_train.iloc[val_idx][features], label=target.iloc[val_idx])

    num_round = 10000
    clf = lgb.train(param, trn_data, num_round, valid_sets = [trn_data, val_data], verbose_eval=100, early_stopping_rounds=100)
    oof[val_idx] = clf.predict(df_train.iloc[val_idx][features], num_iteration=clf.best_iteration)
    fold_importance_df = pd.DataFrame()
    fold_importance_df["feature"] = features
    fold_importance_df["importance"] = clf.feature_importance()
    fold_importance_df["fold"] = fold_ + 1
    feature_importance_df = pd.concat([feature_importance_df, fold_importance_df], axis=0)

    predictions += clf.predict(df_test[features], num_iteration=clf.best_iteration) / folds.n_splits

In [ ]:
cross_validation_lgb = np.sqrt(mean_squared_error(target, oof))
print('Cross-validation score: ' + str(cross_validation_lgb))

In [ ]:
cols = (feature_importance_df[["feature", "importance"]]
        .groupby("feature")
        .mean()
        .sort_values(by="importance", ascending=False)[:1000].index)

best_features = feature_importance_df.loc[feature_importance_df['feature'].isin(cols)]

plt.figure(figsize=(14, 40))
sns.barplot(x="importance",
            y="feature",
            data=best_features.sort_values(by="importance", ascending=False))
plt.title('LightGBM Features (avg over folds)')
plt.tight_layout()
plt.savefig('lgbm_importances.png')

In [ ]:
df_sub = pd.DataFrame({"card_id":df_test["card_id"].values})
df_sub["target"] = predictions
df_sub.to_csv("output/lgbm_{}.csv".format(cross_validation_lgb), index=False)